apps/accounts/urls.py
from django.urls import path
#from .views import RegisterUser

app_name = "accounts"

from . import views

urlpatterns = [
    path('begin', views.begin, name='begin'),
    path('add_user', views.add_user, name='add_user'),
    #path('register/', RegisterUser.as_view(), name='register'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('password_change', views.password_change, name='password_change'),
    path('add_user_profile', views.add_user_profile, name='add_user_profile'),
    path('list_user_profile', views.list_user_profile, name='list_user_profile'),
    path('change_user_profile/<username>/', views.change_user_profile, name='change_user_profile'),
    path('change_user_information/<username>/', views.change_user_information, name='change_user_information'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path    
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('accounts/', include('accounts.urls', namespace='accounts')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model): 
    photo = models.ImageField('Foto', upload_to='photos')
    cell_phone = models.CharField('Celular', max_length=16)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    class Meta:
        verbose_name = 'Perfil do Usuário'
        verbose_name_plural = 'Perfis dos Usuários'
    
    def __str__(self):
        return self.user.username

apps/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User

from .models import UserProfile



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password', 'email']

class UserFormChangeInformation(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['photo', 'cell_phone']

apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import UserForm, UserProfileForm, UserFormChangeInformation
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import UserProfile
from django.contrib.auth import update_session_auth_hash


# Create your views here.
@login_required(login_url='/accounts/user_login')
def begin(request):
    return render(request, 'accounts/begin.html', {})


def add_user(request):
    template_name = 'accounts/add_user.html'
    context = {} 
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.set_password(f.password)
            f.save()
            messages.success(request, 'Usuário salvo com sucesso !!')
    form = UserForm()
    context['form'] = form
    return render(request, template_name, context)



def user_login(request):
    template_name = 'accounts/user_login.html'
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.GET.get('next', '/'))
        else:
            messages.error(request, 'Deu merda !!')
    return render(request, template_name, {})

@login_required(login_url='/accounts/user_login')
def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')

@login_required(login_url='/accounts/user_login')
def password_change(request):
    template_name = 'accounts/password_change.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
        else:
            messages.warning(request, 'Deu merda')
    form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)


def add_user_profile(request):
    template_name = 'accounts/add_user_profile.html'
    context = {}
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            messages.success(request, 'Perfil adicionada com sucesso !!')
    form = UserProfileForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/accounts/user_login')
def list_user_profile(request):
    template_name = 'accounts/list_user_profile.html'
    context = {}
    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        profile = None
    context['profile'] = profile
    return render(request, template_name, context)

@login_required(login_url='/accounts/user_login')
def change_user_profile(request, username):
    template_name = 'accounts/add_user_profile.html'
    context = {}
    profile = UserProfile.objects.get(user__username=username)
    if request.method == "POST":
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Perfil atualizado com sucesso!!')
    form = UserProfileForm(instance=profile)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/accounts/user_login')
def change_user_information(request):
    template_name = 'accounts/change_user_information.html'
    context = {}
    user = User.objects.get(username=f_username)
    if request.method == 'POST':
        form = UserFormChangeInformation(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Informações atualizadoas com sucesso!!')
    form = UserFormChangeInformation(instance=user)
    context['form'] = form
    return render(request, template_name, context)
   
   

templates/accounts/add_user.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
Novo Usuário - {{ block.super }}
{% endblock title %}

{% block body %}
<div class="container">
  {% include 'partials/messages.html' %}
  <form method="POST" action="">
    {% csrf_token %}
    <div class="mb-3">
      <label for="{{ form.first_name.id_for_label }}" class="form-label">first_name</label>
      {{ form.first_name | add_class:"form-control"}}
    </div>
    <div class="mb-3">
      <label for="{{ form.last_name.id_for_label }}" class="form-label">last_name</label>
      {{ form.last_name | add_class:"form-control"}}
    </div>
    <div class="mb-3">
      <label for="{{ form.username.id_for_label }}" class="form-label">username</label>
      {{ form.username | add_class:"form-control"}}
    </div>
    <div class="mb-3">
      <label for="{{ form.password.id_for_label }}" class="form-label">password</label>
      {{ form.password | add_class:"form-control" | attr:"type:password"}}
    </div>
    <div class="mb-3">
      <label for="{{ form.email.id_for_label }}" class="form-label">email</label>
      {{ form.email | add_class:"form-control"}}
    </div>
    <input class="btn btn-primary" type="submit" value="Registrar">
  </form>
</div>
{% endblock body %}

templates/accounts/add_user_profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
Alterar Perfil - {{ block.super}}
{% endblock title %}


{% block body %}
{% include 'partials/messages.html' %}
<div class="container-fluid">
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label for="{{ form.phot.id_for_label}}" class="form-label">Upload de Foto</label>
        {{form.photo | add_class:"form-control-file"}}
    </div>

    <div class="mb-3">
        <label for="{{ form.cell_phone.id_for_label}}" class="form-label">Celular</label>
        {{form.cell_phone | add_class:"form-control"}}
    </div>
    <button type="submit" class="btn btn-primary">Primary</button>
</form>
</div>

{% endblock body %}

templates/accounts/begin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Begin Accounts</h1>
</body>
</html>

templates/accounts/change_user_information.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
Novo Usuário - {{ block.super }}
{% endblock title %}

{% block body %}
<div class="container">
  <h1>Crie sua conta</h1>
  <form action="." method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" value="Registrar">
  </form>
</div>>
{% endblock body %}

templates/accounts/list_user_profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}



{% block title %}
Novo Usuário - {{ block.super }}
{% endblock title %}

{% block body %}

{% if profile %}
<div class="container">
    <hr>
    <div class="media">
        <img class="mr-3" src="{{ user.profile.photo.url }}" alt="Generic placeholder image">
        <div class="media-body">
            <h5 class="mt-0">{{ profile.user.username }}</h5>
            <p>Celular: {{ profile.cell_phone }}</p>
            <p>Email: {{ profile.user.email }}</p>
        </div>
    </div>
    <hr>
    <a class="btn btn-primary" href="{% url 'accounts:change_user_profile' user.username %}">Alterar Perfil</a>
    {% else %}
    <h2>Crie seu perfil</h2>
     <a class="btn btn-primary" href="{% url 'accounts:add_user_profile' %}">Alterar Perfil2</a>

    {% endif %}


</div>

{% endblock body %}

templates/accounts/password_change.html
{% extends 'base.html' %}
{% load widget_tweaks %}



{% block title %}
Trocar Senha - {{ block.super }}
{% endblock title %}



{% block body %}
<div class="container">
    {% include 'partials/messages.html' %}
    <form method="POST" action=".">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Primary</button>
    </form>
</div>


{% endblock body %}

templates/accounts/user_login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Signin Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">

    

    <!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      html,
body {
  height: 100%;
}

body {
  display: flex;
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}
.form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
    </style>

    
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
  <form method="POST" action="user_login">
      {% csrf_token %}
    <img class="mb-4 rounded-circle" src="{% static 'img/task.png' %}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
    <label for="username" class="visually-hidden">Username</label>
    <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus>

    <label for="password" class="visually-hidden">Password</label>
    <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
   
    <button class="w-100 btn btn-lg btn-primary" type="submit">Entrar</button>
    <a class="w-100 btn btn-lg btn-success" href="{% url 'accounts:add_user' %}">Criar uma conta</a>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
  </form>
</main>


    
  </body>
</html>