apps/accounts/urls.py
from django.urls import path
#from .views import RegisterUser

app_name = "accounts"

from . import views

urlpatterns = [
    path('begin', views.begin, name='begin'),
    path('add_user', views.add_user, name='add_user'),
    #path('register/', RegisterUser.as_view(), name='register'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('password_change', views.password_change, name='password_change'),
    path('add_user_profile', views.add_user_profile, name='add_user_profile'),
    path('list_user_profile', views.list_user_profile, name='list_user_profile'),
    path('change_user_profile/<username>/', views.change_user_profile, name='change_user_profile'),
    path('change_user_information/<username>/', views.change_user_information, name='change_user_information'),
]

apps/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"



urlpatterns = [
    path('add_category/', views.add_category, name='add_category'),
    path('list_category/', views.list_category, name='list_category'),
    path('edit_category/<int:id_category>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:id_category>/', views.delete_category, name='delete_category'),
    path('add_task/', views.add_task, name='add_task'),
    path('list_task/', views.list_task, name='list_task'),
    path('edit_task/<int:id_task>/', views.edit_task, name='edit_task'),
    path('delete_task/<int:id_task>/', views.delete_task, name='delete_task'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path    
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('accounts/', include('accounts.urls', namespace='accounts')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField('Nome', max_length=150)
    description = models.TextField('Descrição', blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']
     
    def __str__(self):
        return self.name 


class Tasks(models.Model):
    PRIORITY_CHOICES = (
        ('B', 'Baixa'),
        ('M', 'Media'),
        ('A', 'Alta'),
    )
    STATUS_CHOICES = (
        ('EX', 'Em Execulção'),
        ('PD', 'Pendente'),
        ('CD', 'Concluida'),
    )
    name = models.CharField('Tarefa', max_length=200)
    description = models.TextField('Descrição', blank=True, null=True)
    end_date = models.DateField('Data Final', auto_now=False, auto_now_add=False)
    priority = models.CharField('Prioridade', max_length=1, choices=PRIORITY_CHOICES)
    category = models.ManyToManyField(Category)
    status = models.CharField('Status', max_length=2, choices=STATUS_CHOICES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Tarefa'
        verbose_name_plural = 'Tarefas'
        ordering = ['id']
     
    def __str__(self):
        return self.name 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <title>
        {% block title %}
        Todo App
        {% endblock title %}
    </title>
</head>

<body style="margin-top:67px">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top border" style="background-color:  #ffffff;">
        <div class="container-xl">
            <a class="navbar-brand" href="/">Todo App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07XL"
                aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample07XL">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown07XL" data-toggle="dropdown"
                            aria-expanded="false">Menu</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown07XL">
                            <a class="dropdown-item" href="{% url 'tasks:add_category' %}">Adcionar Categoria</a>
                            <a class="dropdown-item" href="{% url 'tasks:list_category' %}">Listar Categoria</a>
                            <a class="dropdown-item" href="{% url 'tasks:add_task' %}">Adcionar Tarefa</a>
                            <a class="dropdown-item" href="{% url 'tasks:list_task' %}">Listar Tarefa</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline my-2 my-md-0" style="margin-right:5px">
                    <input class="form-control" type="text" placeholder="Search" aria-label="Search">
                </form>

                {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">

                        {% if user.profile.photo.url %}
                        <img src="{{ user.profile.photo.url }}" class="rounded-circle" width="50px" height="50px"
                            alt="">
                        {% else %}
                        <img src="{% static 'download_8RstuUP.png' %}" class="rounded-circle" width="50px" height="50px"
                            alt="">

                        {% endif %}

                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown07XL" data-toggle="dropdown"
                            aria-expanded="false">{{ user.username }}</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown07XL">
                            <a class="dropdown-item" href="{% url 'accounts:list_user_profile' %}">Perfil</a>
                            <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Trocar Senha</a>
                            <a class="dropdown-item"
                                href="{% url 'accounts:change_user_information' user.username %}">Dados</a>
                            <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
                            <a class="dropdown-item" href="{% url 'accounts:add_user' %}">add_user</a>
                        </div>
                    </li>
                </ul>

                {% endif %}


            </div>
        </div>
    </nav>
    {% block body %}

    {% endblock body %}
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/select2.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
        $(document).on('click', '.confirm-delete', function () {
            $("#confirmDeleteModal").attr("caller-id", $(this).attr("id"));
        });

        $(document).on('click', '#confirmDeleteButtonModal', function () {
            var caller = $("#confirmDeleteButtonModal").closest(".modal").attr("caller-id");
            window.location = $("#".concat(caller)).attr("href");
        });

        $("#id_end_date").datepicker({
            dateFormat: "dd/mm/yy"
        });

        $(document).ready(function () {
            $('#id_category').select2();
        });




    </script>

</body>

</html>