apps/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"



urlpatterns = [
    path('add_category/', views.add_category, name='add_category'),
    path('list_category/', views.list_category, name='list_category'),
    path('edit_category/<int:id_category>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:id_category>/', views.delete_category, name='delete_category'),
    path('add_task/', views.add_task, name='add_task'),
    path('list_task/', views.list_task, name='list_task'),
    path('edit_task/<int:id_task>/', views.edit_task, name='edit_task'),
    path('delete_task/<int:id_task>/', views.delete_task, name='delete_task'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path    
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('accounts/', include('accounts.urls', namespace='accounts')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField('Nome', max_length=150)
    description = models.TextField('Descrição', blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']
     
    def __str__(self):
        return self.name 


class Tasks(models.Model):
    PRIORITY_CHOICES = (
        ('B', 'Baixa'),
        ('M', 'Media'),
        ('A', 'Alta'),
    )
    STATUS_CHOICES = (
        ('EX', 'Em Execulção'),
        ('PD', 'Pendente'),
        ('CD', 'Concluida'),
    )
    name = models.CharField('Tarefa', max_length=200)
    description = models.TextField('Descrição', blank=True, null=True)
    end_date = models.DateField('Data Final', auto_now=False, auto_now_add=False)
    priority = models.CharField('Prioridade', max_length=1, choices=PRIORITY_CHOICES)
    category = models.ManyToManyField(Category)
    status = models.CharField('Status', max_length=2, choices=STATUS_CHOICES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Tarefa'
        verbose_name_plural = 'Tarefas'
        ordering = ['id']
     
    def __str__(self):
        return self.name 

apps/tasks/forms.py
from django import forms

from .models import Tasks, Category

class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = Category 
        fields = ('name', 'description')


class TaskForm(forms.ModelForm):
    
    class Meta:
        model = Tasks 
        fields = ('name', 'description', 'end_date', 'end_date', 'priority', 'category', 'status')

apps/tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CategoryForm, TaskForm
from django.contrib import messages
from .models import Category, Tasks
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='/accounts/user_login')
def begin(request):
    return render(request, 'tasks/add_category.html', {})

@login_required(login_url='/accounts/user_login')
def add_category(request):
    template_name = 'tasks/add_category.html'
    context = {}
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.owner = request.user
            f.save()
            messages.success(request, 'Categoria adicionada com sucesso !!')
    form = CategoryForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/accounts/user_login')
def list_category(request):
    template_name = 'tasks/list_categories.html'
    categories = Category.objects.filter(owner=request.user)
    context = {
        'categories': categories
    }
    return render(request, template_name, context)

@login_required(login_url='/accounts/user_login')
def edit_category(request, id_category):
    template_name = 'tasks/add_category.html'
    context = {}
    category = get_object_or_404(Category, id=id_category, owner=request.user)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Categoria editada com sucesso')
            return redirect('tasks:list_category')
    form = CategoryForm(instance=category)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/accounts/user_login')
def delete_category(request, id_category):
    category = Category.objects.get(id=id_category)
    if category.owner == request.user:
        category.delete()
        messages.success(request, 'Categoria excluida com sucesso')
    else:
        messages.error(request, 'Você não tem permissão para excluir essa categoria')
        return redirect('tasks:list_category')
    return redirect('tasks:list_category')

@login_required(login_url='/accounts/user_login')
def add_task(request):
    template_name = 'tasks/add_task.html'
    context = {}
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.owner = request.user
            f.save()
            form.save_m2m()
            messages.success(request, 'Tarefa adicionada com sucesso !!')
            return redirect('tasks:list_task')
           
    form = TaskForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/accounts/user_login')
def list_task(request):
    template_name = 'tasks/list_task.html'
    tasks = Tasks.objects.filter(owner=request.user).exclude(status='CD')
    context = {
        'tasks': tasks
    }
    return render(request, template_name, context)

@login_required(login_url='/accounts/user_login')
def edit_task(request, id_task):
    template_name = 'tasks/add_task.html'
    context = {}
    task = get_object_or_404(Tasks, id=id_task, owner=request.user)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('tasks:list_task')
    form = TaskForm(instance=task)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/accounts/user_login')
def delete_task(request, id_task):
    task = Tasks.objects.get(id=id_task)
    if task.owner == request.user:
        task.delete()
    else:
        messages.error(request, 'Você não tem permissão para excluir essa tarefa')
        return redirect('tasks:list_task')
    return redirect('tasks:list_task')

templates/tasks/add_category.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
add_category - {{ block.super}}
{% endblock title %}


{% block body %}
{% include 'partials/messages.html' %}


<form action="." method="post">
    <br>
    <div class="container-fluid">
    {% csrf_token %}
    <div class="row mb-3">
        <label for="{{ form.name.id_for_label }}" class="col-sm-2 col-form-label">Nome:</label>
        <div class="col-sm-10">
            {{form.name | add_class:"form-control"| attr:"autofocus"}}
        </div>
    </div>
    <div class="row mb-3">
        <label for="{{ form.description.id_for_label }}" class="col-sm-2 col-form-label">Descrição:</label>
        <div class="col-sm-10">
            {{form.description | add_class:"form-control"}}
        </div>
    </div>
   
   
    <button type="submit" class="btn btn-primary">Adcionar</button>
</form>
</div>
{% endblock body %}

templates/tasks/add_task.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
add_task - {{ block.super}}
{% endblock title %}


{% block body %}
<div class="container">
    {% include 'partials/messages.html' %}
    <form action="." method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Nome:</label>
            {{form.name | add_class:"form-control"| attr:"autofocus"}}
        </div>
        <div class="form-group">
            <label for="{{ form.description.id_for_label }}">Descrição:</label>
            {{form.description | add_class:"form-control"}}
        </div>
        <div class="form-group">
            <label for="{{ form.end_date.id_for_label }}">end_date:</label>
            {{form.end_date | add_class:"form-control"}}
        </div>
        <div class="form-group">
            <label for="{{ form.priority.id_for_label }}">priority:</label>
            {{form.priority | add_class:"form-control"}}
        </div>
        <div class="form-group">
            <label for="{{ form.category.id_for_label }}">category:</label>
            {{form.category | add_class:"form-control"}}
        </div>
        <div class="form-group">
            <label for="{{ form.status.id_for_label }}">status:</label>
            {{form.status | add_class:"form-control"}}
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
</div>


</form>
</div>

{% endblock body %}

templates/tasks/list_categories.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
add_category - {{ block.super}}
{% endblock title %}


{% block body %}
{% include 'partials/messages.html' %}
<div class="container-xxl">
    <table class="table table-striped table-hover border">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>

            {% for category in categories  %}
            <tr>
                <th scope="row">{{ category.id }}</th>
                <td>{{ category.name }}</td>
                <td>{{ category.description }}</td>
                <td>
                    <a href="{% url 'tasks:edit_category' category.id %}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
                    <a href="{% url 'tasks:delete_category' category.id  %}" class="btn btn-danger btn-sm confirm-delete" title="Delete" data-toggle="modal" data-target="#confirmDeleteModal" id="deleteButton{{category.id}}"><i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include 'partials/confirm_delete_modal.html' %}
</div>
{% endblock body %}

templates/tasks/list_task.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
add_category - {{ block.super}}
{% endblock title %}


{% block body %}
{% include 'partials/messages.html' %}
<div class="container-xxl">
   
    <table class="table table-striped table-hover border">
        
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">end_date</th>
                <th scope="col">priority</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>

            {% for task in tasks  %}
            <tr>
                <th scope="row">{{ task.id }}</th>
                <td>{{ task.name }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.end_date }}</td>
                <td>{{ task.get_priority_display }}</td>
                <td>
                    <a href="{% url 'tasks:edit_task' task.id %}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
                    <a href="{% url 'tasks:delete_task' task.id  %}" class="btn btn-danger btn-sm confirm-delete" title="Delete" data-toggle="modal" data-target="#confirmDeleteModal" id="deleteButton{{task.id}}"><i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include 'partials/confirm_delete_modal.html' %}
</div>
{% endblock body %}